basePath: /api
definitions:
  models.UserResponse:
    properties:
      email:
        type: string
      id:
        type: string
      name:
        type: string
      photo:
        type: string
      provider:
        type: string
      role:
        type: string
      verified:
        type: boolean
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is a sample goplock server.
  title: Goplock API
  version: v1
paths:
  /auth/forgot-password:
    post:
      description: Forgot Password
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Forgot Password
      tags:
      - Auth
  /auth/google:
    get:
      description: Google GoogleOAuth
      parameters:
      - description: Authorization Code
        in: query
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Google GoogleOAuth
      tags:
      - Auth
  /auth/login:
    post:
      description: Login User
      parameters:
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      responses: {}
      summary: Login
      tags:
      - Auth
  /auth/logout:
    delete:
      description: Logout User
      responses:
        "204":
          description: No Content
        "403":
          description: Forbidden
      security:
      - BearerAuth: []
      summary: Logout
      tags:
      - Auth
  /auth/password:
    patch:
      description: Change Password
      parameters:
      - description: Password
        in: formData
        name: oldPassword
        required: true
        type: string
      - description: Password
        in: formData
        name: newPassword
        required: true
        type: string
      - description: Password Confirm
        in: formData
        name: newPasswordConfirm
        required: true
        type: string
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      summary: Change Password
      tags:
      - Auth
  /auth/refresh:
    post:
      description: Refresh Access Token
      responses: {}
      summary: Refresh Access Token
      tags:
      - Auth
  /auth/register:
    post:
      description: Register new User
      parameters:
      - description: Name
        in: formData
        name: name
        required: true
        type: string
      - description: Email
        in: formData
        name: email
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Password Confirmation
        in: formData
        name: passwordConfirmation
        required: true
        type: string
      - description: Photo
        in: formData
        name: photo
        type: string
      responses: {}
      summary: Register
      tags:
      - Auth
  /auth/reset-password/{resetToken}:
    patch:
      description: Reset Password
      parameters:
      - description: Reset Token
        in: path
        name: resetToken
        required: true
        type: string
      - description: Password
        in: formData
        name: password
        required: true
        type: string
      - description: Password Confirm
        in: formData
        name: passwordConfirm
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Reset Password
      tags:
      - Auth
  /auth/verify-email:
    post:
      description: Send Email Verification
      responses:
        "200":
          description: OK
      security:
      - BearerAuth: []
      - BearerAuth: []
      summary: Send Email Verification
      tags:
      - Auth
  /auth/verify-email/{code}:
    get:
      description: Verify Email
      parameters:
      - description: Verification Code
        in: path
        name: code
        required: true
        type: string
      responses:
        "200":
          description: OK
      summary: Verify Email
      tags:
      - Auth
  /users:
    get:
      description: Get all Users
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.UserResponse'
            type: array
      security:
      - BearerAuth: []
      summary: Get Users
      tags:
      - User
  /users/{id}:
    get:
      description: Get User by ID
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
      security:
      - BearerAuth: []
      summary: Get User
      tags:
      - User
  /users/me:
    get:
      description: Get current User
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.UserResponse'
      security:
      - BearerAuth: []
      summary: Get Me
      tags:
      - User
produces:
- application/json
schemes:
- http
- https
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token.
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
